# 工作流名称
name: Sync Fork

# 触发工作流的事件
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：检出你的 Fork 仓库代码
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 步骤2：同步上游仓库的更新
      - name: Sync Upstream
        run: |
          # -----------------------------------------------------------------
          # 注意：请根据你的实际情况修改下面的 'main' 分支为你的默认分支名
          # 常见的有 'main', 'master' 等
          BRANCH_NAME="main"
          # -----------------------------------------------------------------

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # [修正后的命令]
          # 先通过 --json parent 获取整个 parent 对象
          # 再通过 --jq .parent.url 从中提取 url
          UPSTREAM_URL=$(gh repo view --json parent --jq .parent.url)
          
          if [ -z "$UPSTREAM_URL" ] || [ "$UPSTREAM_URL" == "null" ]; then
            echo "This repository is not a fork. Skipping sync."
            exit 0
          fi

          echo "Upstream URL is $UPSTREAM_URL"
          
          git remote add upstream $UPSTREAM_URL
          git fetch upstream

          git checkout $BRANCH_NAME
          
          # 使用 --ff-only 进行快进合并，这是一个安全的操作
          git merge --ff-only "upstream/$BRANCH_NAME"

          # git push 会使用由 actions/checkout 配置好的凭据
          git push origin $BRANCH_NAME
        env:
          # gh CLI 命令需要 GITHUB_TOKEN 来进行认证
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
